# Generated by Django 3.2 on 2023-03-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0002_walletmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.BigIntegerField(default=0)),
                ('transaction_desc', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.transactiontypemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
