# Generated by Django 3.2 on 2023-03-29 21:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmodel',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='256700000000', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
