# Generated by Django 3.2 on 2023-03-30 13:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230329_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='256700000000', max_length=128, region=None),
        ),
    ]
