# Generated by Django 3.2 on 2023-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_usersmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
